name: Project live
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go version: 'v1.13.7'
      - name: Check Go version
        run: go version
      - name: List files
        run:  |
          ls -a
      - name: Getting dependencies
        run: |
          go get github.com/DATA-DOG/go-sqlmock
      - if: ${{success()}}
        run: |
          go get github.com/stretchr/testify
      - if: ${{success()}}
        name: Go into logger directory and run test
        run: |
          cd logger/
          go test -v
      - if: ${{success()}}
        name: Go into quotation directory and run test
        run: |
          cd ../quotation/
          go test -v
      - if: ${{failure()}}
        name: Creating issues if failed
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test-results/**/*.xml
